// TODO CHANGE

#define PIN_SERVO_BASE 9
#define PIN_SERVO_VERTICAL 11
#define PIN_HELICOPTER 5

#define PIN_MOVE_TASSEL_FWD 12
#define PIN_RAPIDLY_WIPE_TASSEL 10
#define PIN_REVERSE_TASSEL_SPIN 8

#define LIMIT_BASE_MIN 90
#define LIMIT_BASE_MAX 0
#define LIMIT_VERT_MIN 130
#define LIMIT_VERT_MAX 40

#define DELAY_MOVE_FWD 5000
#define DELAY_WIPE_TASSEL 250
